"""
SystemVerilog Assertions (SVA) Exporter

Generates a SystemVerilog assertions module from an FSM definition.
The module includes:
  - assert property: one-hot check (only one state active)
  - assert property: no illegal state reached
  - assert property: each transition is valid
  - cover property: each state is reachable
  - cover property: each transition is taken
"""

from typing import Dict, List, Optional

from app.utils.exceptions import ExportException


class SVAExporter:
    """Generates a SystemVerilog assertions module from an FSM definition."""

    def export(
        self,
        definition: dict,
        fsm_type: str,
        name: str,
        options: Optional[Dict] = None,
    ) -> str:
        """
        Generate a SystemVerilog assertions module for the given FSM.

        Args:
            definition: FSM definition dict with states, transitions, outputs,
                        encodings.
            fsm_type:   'moore' or 'mealy'
            name:       FSM name (used as module name)
            options:    Optional settings:
                          include_coverage (bool, default True)
                          clock_name       (str,  default "clk")
                          reset_name       (str,  default "rst_n")

        Returns:
            SystemVerilog source code as a string.

        Raises:
            ExportException: If the definition is invalid.
        """
        options = options or {}
        include_coverage: bool = options.get("include_coverage", True)
        clock_name: str = options.get("clock_name", "clk")
        reset_name: str = options.get("reset_name", "rst_n")

        states: List[str] = definition.get("states", [])
        transitions: List[Dict] = definition.get("transitions", [])
        encodings: Dict[str, str] = definition.get("encodings", {})

        if not states:
            raise ExportException("FSM has no states to export")

        import math

        state_bits = max(math.ceil(math.log2(max(len(states), 2))), 1)

        # Fall back to binary encoding when none provided
        def enc(state: str, idx: int) -> str:
            return encodings.get(state, format(idx, f"0{state_bits}b"))

        module_name = self._sanitize_name(name) + "_sva"

        lines: List[str] = []

        # ---------------------------------------------------------------
        # File header
        # ---------------------------------------------------------------
        lines.append("// ===========================================")
        lines.append(f"// SVA Assertions Module: {name}")
        lines.append(f"// Type: {fsm_type.upper()}")
        lines.append(f"// States: {len(states)}")
        lines.append("// Generated by GrayFSM")
        lines.append("// ===========================================")
        lines.append("")

        # ---------------------------------------------------------------
        # Module declaration
        # ---------------------------------------------------------------
        lines.append(f"module {module_name} (")
        lines.append(f"    input  logic {clock_name},")
        lines.append(f"    input  logic {reset_name},")
        lines.append(f"    input  logic [{state_bits - 1}:0] current_state")
        if fsm_type == "mealy":
            # Collect unique inputs for Mealy coverage
            inputs = sorted({t.get("input") for t in transitions if t.get("input")})
            for inp in inputs:
                lines.append(f"    , input  logic {self._sanitize_name(inp)}")
        lines.append(");")
        lines.append("")

        # ---------------------------------------------------------------
        # State parameter declarations
        # ---------------------------------------------------------------
        lines.append("    // State encoding parameters")
        for i, state in enumerate(states):
            sanitized = self._sanitize_name(state)
            code = enc(state, i)
            lines.append(f"    localparam [{state_bits - 1}:0] {sanitized} = {state_bits}'b{code};")
        lines.append("")

        # ---------------------------------------------------------------
        # Default clocking block
        # ---------------------------------------------------------------
        lines.append(f"    default clocking fsm_clk @(posedge {clock_name});")
        lines.append("    endclocking")
        lines.append("")

        # ---------------------------------------------------------------
        # Helper: build the valid-state set expression
        #   ( (current_state == S0) || (current_state == S1) || ... )
        # ---------------------------------------------------------------
        valid_state_expr = " || ".join(
            f"(current_state == {self._sanitize_name(s)})" for s in states
        )

        # ---------------------------------------------------------------
        # Assertion 1 (one-hot): only one state active
        # Meaningful only for one-hot encoding; emit a note when the
        # encoding is not one-hot so the file is still syntactically valid.
        # ---------------------------------------------------------------
        lines.append("    // -----------------------------------------------")
        lines.append("    // Assertion 1: Only one state active (one-hot check)")
        lines.append("    // -----------------------------------------------")

        # Build one-hot check: exactly one bit is set
        # $onehot(current_state) is the built-in SV operator
        lines.append("    ap_onehot_state: assert property (")
        lines.append(f"        disable iff (!{reset_name})")
        lines.append("        $onehot(current_state)")
        lines.append('    ) else $error("One-hot violation: current_state = %b", current_state);')
        lines.append("")

        # ---------------------------------------------------------------
        # Assertion 2: no illegal state (state always in valid set)
        # ---------------------------------------------------------------
        lines.append("    // -----------------------------------------------")
        lines.append("    // Assertion 2: No illegal state reached")
        lines.append("    // -----------------------------------------------")
        lines.append("    ap_valid_state: assert property (")
        lines.append(f"        disable iff (!{reset_name})")
        lines.append(f"        ({valid_state_expr})")
        lines.append(
            '    ) else $error("Illegal state reached: current_state = %b", current_state);'
        )
        lines.append("")

        # ---------------------------------------------------------------
        # Assertion 3: each transition is valid
        # For every (from_state, input) pair, the next state must be in
        # the defined to_state(s) for that pair.
        # ---------------------------------------------------------------
        lines.append("    // -----------------------------------------------")
        lines.append("    // Assertion 3: Each transition is valid")
        lines.append("    // -----------------------------------------------")

        # Group transitions by (from_state, input) -> set of to_states
        import collections
        from typing import DefaultDict

        trans_map: DefaultDict = collections.defaultdict(set)
        for t in transitions:
            from_s = t.get("from_state", "")
            to_s = t.get("to_state", "")
            inp = t.get("input")  # may be None
            trans_map[(from_s, inp)].add(to_s)

        for idx, ((from_s, inp), to_states) in enumerate(sorted(trans_map.items())):
            san_from = self._sanitize_name(from_s)
            to_expr = " || ".join(
                f"(current_state == {self._sanitize_name(ts)})" for ts in sorted(to_states)
            )
            if inp:
                san_inp = self._sanitize_name(inp)
                antecedent = f"(current_state == {san_from}) && {san_inp}"
            else:
                antecedent = f"(current_state == {san_from})"

            prop_name = f"ap_trans_{idx}_{san_from}"
            lines.append(f"    {prop_name}: assert property (")
            lines.append(f"        disable iff (!{reset_name})")
            lines.append(f"        ({antecedent}) |=> ({to_expr})")
            lines.append(
                f'    ) else $error("Invalid transition from {from_s}: '
                f'next current_state = %b", current_state);'
            )
            lines.append("")

        # ---------------------------------------------------------------
        # Coverage properties (optional)
        # ---------------------------------------------------------------
        if include_coverage:
            lines.append("    // -----------------------------------------------")
            lines.append("    // Coverage: each state is reached")
            lines.append("    // -----------------------------------------------")
            for state in states:
                san = self._sanitize_name(state)
                lines.append(f"    cp_reach_{san}: cover property (")
                lines.append(f"        disable iff (!{reset_name})")
                lines.append(f"        (current_state == {san})")
                lines.append("    );")
            lines.append("")

            lines.append("    // -----------------------------------------------")
            lines.append("    // Coverage: each transition is taken")
            lines.append("    // -----------------------------------------------")
            for t_idx, t in enumerate(transitions):
                from_s = t.get("from_state", "")
                to_s = t.get("to_state", "")
                inp = t.get("input")
                san_from = self._sanitize_name(from_s)
                san_to = self._sanitize_name(to_s)
                if inp:
                    san_inp = self._sanitize_name(inp)
                    antecedent = f"(current_state == {san_from}) && {san_inp}"
                else:
                    antecedent = f"(current_state == {san_from})"
                prop_name = f"cp_trans_{t_idx}_{san_from}_to_{san_to}"
                lines.append(f"    {prop_name}: cover property (")
                lines.append(f"        disable iff (!{reset_name})")
                lines.append(f"        ({antecedent}) ##1 (current_state == {san_to})")
                lines.append("    );")
            lines.append("")

        lines.append("endmodule")
        lines.append("")

        return "\n".join(lines)

    @staticmethod
    def _sanitize_name(name: str) -> str:
        """
        Sanitize a name for use as a SystemVerilog identifier.
        Replaces non-alphanumeric characters with underscores.
        """
        sanitized = ""
        for ch in name:
            if ch.isalnum() or ch == "_":
                sanitized += ch
            else:
                sanitized += "_"
        if sanitized and sanitized[0].isdigit():
            sanitized = "_" + sanitized
        return sanitized or "_unnamed"
