"""
Verilog HDL Exporter

Generates synthesizable Verilog code from an FSM definition.
Produces a standard always @(posedge clk) state machine template.
"""

from typing import Dict, List, Optional

from app.utils.exceptions import ExportException


class VerilogExporter:
    """Generates Verilog HDL code from FSM definition"""

    def export(
        self,
        definition: dict,
        fsm_type: str,
        name: str,
        options: Optional[Dict] = None,
    ) -> str:
        """
        Generate Verilog HDL for the given FSM.

        Args:
            definition: FSM definition dict with states, transitions, outputs, encodings
            fsm_type: 'moore' or 'mealy'
            name: FSM name (used as module name)
            options: Optional settings (module_name, include_comments, style)

        Returns:
            Verilog source code as a string

        Raises:
            ExportException: If the definition is invalid
        """
        options = options or {}
        module_name = options.get("module_name", self._sanitize_name(name))
        include_comments = options.get("include_comments", True)
        include_synthesis_pragmas = options.get("include_synthesis_pragmas", True)
        target_tool = options.get("target_tool", "generic")

        states = definition.get("states", [])
        transitions = definition.get("transitions", [])
        outputs = definition.get("outputs", {})
        initial_state = definition.get("initial_state", "")
        encodings = definition.get("encodings", {})

        if not states:
            raise ExportException("FSM has no states to export")

        # Determine bit widths
        import math

        state_bits = max(math.ceil(math.log2(max(len(states), 2))), 1)

        # Collect unique inputs
        inputs = set()
        for t in transitions:
            inp = t.get("input")
            if inp:
                inputs.add(inp)

        # Collect unique output values to determine output bit width
        output_values = set(outputs.values()) if outputs else set()
        output_bits = 1
        if output_values:
            max_len = max(len(v) for v in output_values)
            output_bits = max(max_len, 1)

        lines = []

        if include_comments:
            lines.append("// ===========================================")
            lines.append(f"// FSM: {name}")
            lines.append(f"// Type: {fsm_type.upper()}")
            lines.append(f"// States: {len(states)}")
            lines.append("// Generated by GrayFSM")
            lines.append("// ===========================================")
            lines.append("")

        # Module declaration
        input_ports = ", ".join(sorted(inputs)) if inputs else ""
        lines.append(f"module {module_name} (")
        lines.append("    input  wire clk,")
        lines.append("    input  wire rst_n,")
        if input_ports:
            for inp in sorted(inputs):
                lines.append(f"    input  wire {self._sanitize_name(inp)},")
        lines.append(f"    output reg [{output_bits - 1}:0] out")
        lines.append(");")
        lines.append("")

        # State parameter declarations
        if include_comments:
            lines.append("    // State encoding")
        for i, state in enumerate(states):
            encoding = encodings.get(state, format(i, f"0{state_bits}b"))
            sanitized = self._sanitize_name(state)
            lines.append(
                f"    localparam [{state_bits - 1}:0] {sanitized} = {state_bits}'b{encoding};"
            )
        lines.append("")

        # State registers
        if include_synthesis_pragmas:
            lines.append('    (* fsm_encoding = "gray" *)')
            if target_tool == "vivado":
                lines.append('    (* fsm_safe_state = "default_state" *)')
        lines.append(f"    reg [{state_bits - 1}:0] current_state, next_state;")
        lines.append("")

        # Sequential block: state register
        if include_comments:
            lines.append("    // Sequential: state register")
        lines.append("    always @(posedge clk or negedge rst_n) begin")
        lines.append("        if (!rst_n)")
        init_sanitized = self._sanitize_name(initial_state)
        lines.append(f"            current_state <= {init_sanitized};")
        lines.append("        else")
        lines.append("            current_state <= next_state;")
        lines.append("    end")
        lines.append("")

        # Combinational block: next state logic
        if include_comments:
            lines.append("    // Combinational: next state logic")
        lines.append("    always @(*) begin")
        lines.append("        next_state = current_state; // default: hold")
        if include_synthesis_pragmas and target_tool == "quartus":
            lines.append("        /* synthesis full_case parallel_case */")
        elif include_synthesis_pragmas:
            lines.append("        // synopsys full_case parallel_case")
        lines.append("        case (current_state)")
        self._generate_next_state_logic(lines, states, transitions, encodings, state_bits)
        lines.append("        endcase")
        lines.append("    end")
        lines.append("")

        # Output logic
        if include_comments:
            if fsm_type == "moore":
                lines.append("    // Moore output logic (depends only on state)")
            else:
                lines.append("    // Mealy output logic (depends on state and input)")
        lines.append("    always @(*) begin")
        if fsm_type == "moore":
            if include_synthesis_pragmas and target_tool == "quartus":
                lines.append("        /* synthesis full_case parallel_case */")
            elif include_synthesis_pragmas:
                lines.append("        // synopsys full_case parallel_case")
            lines.append("        case (current_state)")
            for state in states:
                sanitized = self._sanitize_name(state)
                output_val = outputs.get(state, "0" * output_bits)
                lines.append(f"            {sanitized}: out = {output_bits}'b{output_val};")
            lines.append(f"            default: out = {output_bits}'b{'0' * output_bits};")
            lines.append("        endcase")
        else:
            # Mealy: output depends on state + input
            lines.append(f"        out = {output_bits}'b{'0' * output_bits}; // default")
            if include_synthesis_pragmas and target_tool == "quartus":
                lines.append("        /* synthesis full_case parallel_case */")
            elif include_synthesis_pragmas:
                lines.append("        // synopsys full_case parallel_case")
            lines.append("        case (current_state)")
            self._generate_mealy_output_logic(lines, states, transitions, output_bits)
            lines.append("        endcase")
        lines.append("    end")
        lines.append("")

        lines.append("endmodule")
        lines.append("")

        return "\n".join(lines)

    def _generate_next_state_logic(
        self,
        lines: list,
        states: List[str],
        transitions: List[Dict],
        encodings: dict,
        state_bits: int,
    ) -> None:
        """Generate case items for next-state logic."""
        # Group transitions by from_state
        trans_by_state: Dict[str, List[Dict]] = {}
        for t in transitions:
            fs = t.get("from_state", "")
            trans_by_state.setdefault(fs, []).append(t)

        for state in states:
            sanitized = self._sanitize_name(state)
            state_trans = trans_by_state.get(state, [])
            if not state_trans:
                continue

            lines.append(f"            {sanitized}: begin")
            for t in state_trans:
                to_state = self._sanitize_name(t.get("to_state", ""))
                inp = t.get("input")
                if inp:
                    lines.append(f"                if ({self._sanitize_name(inp)})")
                    lines.append(f"                    next_state = {to_state};")
                else:
                    lines.append(f"                next_state = {to_state};")
            lines.append("            end")

        lines.append(f"            default: next_state = {self._sanitize_name(states[0])};")

    def _generate_mealy_output_logic(
        self,
        lines: list,
        states: List[str],
        transitions: List[Dict],
        output_bits: int,
    ) -> None:
        """Generate Mealy output logic (state + input dependent)."""
        trans_by_state: Dict[str, List[Dict]] = {}
        for t in transitions:
            fs = t.get("from_state", "")
            trans_by_state.setdefault(fs, []).append(t)

        for state in states:
            sanitized = self._sanitize_name(state)
            state_trans = trans_by_state.get(state, [])
            if not state_trans:
                continue

            lines.append(f"            {sanitized}: begin")
            for t in state_trans:
                inp = t.get("input")
                out_val = t.get("output", "0" * output_bits)
                if out_val and inp:
                    lines.append(f"                if ({self._sanitize_name(inp)})")
                    lines.append(f"                    out = {output_bits}'b{out_val};")
            lines.append("            end")

        lines.append(f"            default: out = {output_bits}'b{'0' * output_bits};")

    @staticmethod
    def _sanitize_name(name: str) -> str:
        """
        Sanitize a name for use as a Verilog identifier.
        Replaces non-alphanumeric characters with underscores.
        """
        sanitized = ""
        for ch in name:
            if ch.isalnum() or ch == "_":
                sanitized += ch
            else:
                sanitized += "_"
        # Ensure it starts with a letter or underscore
        if sanitized and sanitized[0].isdigit():
            sanitized = "_" + sanitized
        return sanitized or "_unnamed"
