"""
VHDL Exporter

Generates synthesizable VHDL code from an FSM definition.
Produces a standard process(clk) state machine template.
"""

from typing import Dict, List, Optional

from app.utils.exceptions import ExportException


class VHDLExporter:
    """Generates VHDL code from FSM definition"""

    def export(
        self,
        definition: dict,
        fsm_type: str,
        name: str,
        options: Optional[Dict] = None,
    ) -> str:
        """
        Generate VHDL for the given FSM.

        Args:
            definition: FSM definition dict with states, transitions, outputs, encodings
            fsm_type: 'moore' or 'mealy'
            name: FSM name (used as entity name)
            options: Optional settings (module_name, include_comments, style)

        Returns:
            VHDL source code as a string

        Raises:
            ExportException: If the definition is invalid
        """
        options = options or {}
        entity_name = options.get("module_name", self._sanitize_name(name))
        include_comments = options.get("include_comments", True)
        include_synthesis_pragmas = options.get("include_synthesis_pragmas", True)
        target_tool = options.get("target_tool", "generic")

        states = definition.get("states", [])
        transitions = definition.get("transitions", [])
        outputs = definition.get("outputs", {})
        initial_state = definition.get("initial_state", "")

        if not states:
            raise ExportException("FSM has no states to export")

        # Collect unique inputs
        inputs = set()
        for t in transitions:
            inp = t.get("input")
            if inp:
                inputs.add(inp)

        # Determine output bit width
        output_values = set(outputs.values()) if outputs else set()
        output_bits = 1
        if output_values:
            max_len = max(len(v) for v in output_values)
            output_bits = max(max_len, 1)

        lines = []

        if include_comments:
            lines.append("-- ===========================================")
            lines.append(f"-- FSM: {name}")
            lines.append(f"-- Type: {fsm_type.upper()}")
            lines.append(f"-- States: {len(states)}")
            lines.append("-- Generated by GrayFSM")
            lines.append("-- ===========================================")
            lines.append("")

        # Library declarations
        lines.append("library IEEE;")
        lines.append("use IEEE.STD_LOGIC_1164.ALL;")
        lines.append("")

        # Entity declaration
        lines.append(f"entity {entity_name} is")
        lines.append("    port (")
        lines.append("        clk   : in  STD_LOGIC;")
        lines.append("        rst_n : in  STD_LOGIC;")
        for inp in sorted(inputs):
            sanitized_inp = self._sanitize_name(inp)
            lines.append(f"        {sanitized_inp:6s}: in  STD_LOGIC;")
        if output_bits == 1:
            lines.append("        fsm_out : out STD_LOGIC")
        else:
            lines.append(f"        fsm_out : out STD_LOGIC_VECTOR({output_bits - 1} downto 0)")
        lines.append("    );")
        lines.append(f"end entity {entity_name};")
        lines.append("")

        # Architecture
        lines.append(f"architecture behavioral of {entity_name} is")
        lines.append("")

        # State type declaration
        sanitized_states = [self._sanitize_name(s) for s in states]
        state_list = ", ".join(sanitized_states)
        lines.append(f"    type state_type is ({state_list});")
        lines.append("    signal current_state, next_state : state_type;")
        lines.append("")

        # Synthesis pragmas for FSM encoding
        if include_synthesis_pragmas:
            lines.append("    attribute fsm_encoding : string;")
            lines.append('    attribute fsm_encoding of current_state : signal is "gray";')
            if target_tool == "vivado":
                lines.append("    attribute fsm_safe_state : string;")
                lines.append(
                    '    attribute fsm_safe_state of current_state : signal is "default_state";'
                )
            lines.append("")

        lines.append("begin")
        lines.append("")

        # Sequential process: state register
        if include_comments:
            lines.append("    -- Sequential: state register")
        init_sanitized = self._sanitize_name(initial_state)
        lines.append("    state_reg: process(clk, rst_n)")
        lines.append("    begin")
        lines.append("        if rst_n = '0' then")
        lines.append(f"            current_state <= {init_sanitized};")
        lines.append("        elsif rising_edge(clk) then")
        lines.append("            current_state <= next_state;")
        lines.append("        end if;")
        lines.append("    end process state_reg;")
        lines.append("")

        # Combinational process: next state logic
        if include_comments:
            lines.append("    -- Combinational: next state logic")
        sensitivity = "current_state"
        if inputs:
            sensitivity += ", " + ", ".join(self._sanitize_name(i) for i in sorted(inputs))
        lines.append(f"    next_state_logic: process({sensitivity})")
        lines.append("    begin")
        lines.append("        next_state <= current_state; -- default: hold")
        lines.append("        case current_state is")
        self._generate_next_state_logic(lines, states, transitions)
        lines.append("        end case;")
        lines.append("    end process next_state_logic;")
        lines.append("")

        # Output process
        if include_comments:
            if fsm_type == "moore":
                lines.append("    -- Moore output logic (depends only on state)")
            else:
                lines.append("    -- Mealy output logic (depends on state and input)")

        if fsm_type == "moore":
            lines.append("    output_logic: process(current_state)")
            lines.append("    begin")
            lines.append("        case current_state is")
            for state in states:
                sanitized = self._sanitize_name(state)
                output_val = outputs.get(state, "0" * output_bits)
                if output_bits == 1:
                    lines.append(f"            when {sanitized} => fsm_out <= '{output_val}';")
                else:
                    lines.append(f'            when {sanitized} => fsm_out <= "{output_val}";')
            if output_bits == 1:
                lines.append(f"            when others => fsm_out <= '{'0' * output_bits}';")
            else:
                lines.append(f'            when others => fsm_out <= "{"0" * output_bits}";')
            lines.append("        end case;")
            lines.append("    end process output_logic;")
        else:
            # Mealy output
            mealy_sensitivity = "current_state"
            if inputs:
                mealy_sensitivity += ", " + ", ".join(
                    self._sanitize_name(i) for i in sorted(inputs)
                )
            lines.append(f"    output_logic: process({mealy_sensitivity})")
            lines.append("    begin")
            if output_bits == 1:
                lines.append("        fsm_out <= '0'; -- default")
            else:
                lines.append(f'        fsm_out <= "{"0" * output_bits}"; -- default')
            lines.append("        case current_state is")
            self._generate_mealy_output_logic(lines, states, transitions, output_bits)
            lines.append("        end case;")
            lines.append("    end process output_logic;")

        lines.append("")
        lines.append("end architecture behavioral;")
        lines.append("")

        return "\n".join(lines)

    def _generate_next_state_logic(
        self,
        lines: list,
        states: List[str],
        transitions: List[Dict],
    ) -> None:
        """Generate VHDL case items for next-state logic."""
        trans_by_state: Dict[str, List[Dict]] = {}
        for t in transitions:
            fs = t.get("from_state", "")
            trans_by_state.setdefault(fs, []).append(t)

        for state in states:
            sanitized = self._sanitize_name(state)
            state_trans = trans_by_state.get(state, [])
            if not state_trans:
                continue

            lines.append(f"            when {sanitized} =>")
            for t in state_trans:
                to_state = self._sanitize_name(t.get("to_state", ""))
                inp = t.get("input")
                if inp:
                    lines.append(f"                if {self._sanitize_name(inp)} = '1' then")
                    lines.append(f"                    next_state <= {to_state};")
                    lines.append("                end if;")
                else:
                    lines.append(f"                next_state <= {to_state};")

        lines.append("            when others =>")
        lines.append(f"                next_state <= {self._sanitize_name(states[0])};")

    def _generate_mealy_output_logic(
        self,
        lines: list,
        states: List[str],
        transitions: List[Dict],
        output_bits: int,
    ) -> None:
        """Generate VHDL Mealy output logic."""
        trans_by_state: Dict[str, List[Dict]] = {}
        for t in transitions:
            fs = t.get("from_state", "")
            trans_by_state.setdefault(fs, []).append(t)

        for state in states:
            sanitized = self._sanitize_name(state)
            state_trans = trans_by_state.get(state, [])
            if not state_trans:
                continue

            lines.append(f"            when {sanitized} =>")
            for t in state_trans:
                inp = t.get("input")
                out_val = t.get("output", "0" * output_bits)
                if inp and out_val:
                    lines.append(f"                if {self._sanitize_name(inp)} = '1' then")
                    if output_bits == 1:
                        lines.append(f"                    fsm_out <= '{out_val}';")
                    else:
                        lines.append(f'                    fsm_out <= "{out_val}";')
                    lines.append("                end if;")

        lines.append("            when others =>")
        if output_bits == 1:
            lines.append("                fsm_out <= '0';")
        else:
            lines.append(f'                fsm_out <= "{"0" * output_bits}";')

    @staticmethod
    def _sanitize_name(name: str) -> str:
        """
        Sanitize a name for use as a VHDL identifier.
        Replaces non-alphanumeric characters with underscores.
        """
        sanitized = ""
        for ch in name:
            if ch.isalnum() or ch == "_":
                sanitized += ch
            else:
                sanitized += "_"
        # VHDL identifiers must start with a letter
        if sanitized and (sanitized[0].isdigit() or sanitized[0] == "_"):
            sanitized = "s_" + sanitized
        # Remove trailing underscores (illegal in VHDL)
        sanitized = sanitized.rstrip("_")
        # Remove double underscores (illegal in VHDL)
        while "__" in sanitized:
            sanitized = sanitized.replace("__", "_")
        return sanitized or "s_unnamed"
