"""Initial migration

Revision ID: 5c754bee004e
Revises: 
Create Date: 2025-12-06 16:10:45.658382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5c754bee004e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('parent_category_id', sa.UUID(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('fsm_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['parent_category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('fsms',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('fsm_type', sa.Enum('moore', 'mealy', name='fsm_type'), nullable=False),
    sa.Column('definition', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('state_count', sa.Integer(), nullable=False),
    sa.Column('transition_count', sa.Integer(), nullable=False),
    sa.Column('initial_state', sa.String(length=100), nullable=False),
    sa.Column('bit_width', sa.Integer(), nullable=False),
    sa.Column('encoding_type', sa.String(length=50), nullable=True),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('tags', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('visibility', sa.Enum('private', 'public', 'unlisted', 'example', name='fsm_visibility'), nullable=True),
    sa.Column('is_optimized', sa.Boolean(), nullable=True),
    sa.Column('optimization_algorithm', sa.String(length=100), nullable=True),
    sa.Column('dummy_state_count', sa.Integer(), nullable=True),
    sa.Column('avg_hamming_distance', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=True),
    sa.Column('fork_count', sa.Integer(), nullable=True),
    sa.Column('export_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_fsms_category', 'fsms', ['category_id'], unique=False)
    op.create_index('idx_fsms_is_optimized', 'fsms', ['is_optimized'], unique=False)
    op.create_index('idx_fsms_type', 'fsms', ['fsm_type'], unique=False)
    op.create_index('idx_fsms_visibility', 'fsms', ['visibility'], unique=False)
    op.create_table('algorithm_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('original_fsm_id', sa.UUID(), nullable=False),
    sa.Column('optimized_fsm_id', sa.UUID(), nullable=True),
    sa.Column('algorithm', sa.Enum('greedy', 'bfs_optimal', 'global_sa', 'global_ga', 'hybrid', name='algorithm_name'), nullable=False),
    sa.Column('algorithm_version', sa.String(length=50), nullable=True),
    sa.Column('algorithm_parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('dummy_states_added', sa.Integer(), nullable=True),
    sa.Column('total_states_final', sa.Integer(), nullable=False),
    sa.Column('avg_hamming_before', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('avg_hamming_after', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('improvement_percentage', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('execution_time_ms', sa.Integer(), nullable=False),
    sa.Column('memory_used_mb', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('executed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['optimized_fsm_id'], ['fsms.id'], ),
    sa.ForeignKeyConstraint(['original_fsm_id'], ['fsms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('algorithm_results')
    op.drop_index('idx_fsms_visibility', table_name='fsms')
    op.drop_index('idx_fsms_type', table_name='fsms')
    op.drop_index('idx_fsms_is_optimized', table_name='fsms')
    op.drop_index('idx_fsms_category', table_name='fsms')
    op.drop_table('fsms')
    op.drop_table('categories')
    # ### end Alembic commands ###
